Repository superfluid-finance/protocol-monorepo, pull requests merged in 2023-10, with the labels that each got.

#1710 [ETHEREUM-CONTRACTS] use eip 1967 slot for admin
  packages/ethereum-contracts/CHANGELOG.md
  packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperToken.sol
  packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperTokenFactory.sol
  packages/ethereum-contracts/contracts/interfaces/superfluid/ISuperfluid.sol
  packages/ethereum-contracts/contracts/mocks/SuperTokenMock.sol
  packages/ethereum-contracts/contracts/superfluid/SuperToken.sol
  packages/ethereum-contracts/contracts/superfluid/SuperTokenFactory.sol
  packages/ethereum-contracts/contracts/utils/SuperfluidFrameworkDeployer.sol
  packages/ethereum-contracts/test/foundry/FoundrySuperfluidTester.sol
  packages/ethereum-contracts/test/foundry/gov/SuperfluidGovernanceII.t.sol
  packages/ethereum-contracts/test/foundry/superfluid/SuperToken.t.sol
  packages/ethereum-contracts/test/foundry/superfluid/Superfluid.t.sol
Labels: Tag: TechDebt, Project: PROTOCOL-EVMv1

#1712 [WORKFLOWS] Update call.check-query-schema-against-subgraph.yml
  .github/workflows/call.check-query-schema-against-subgraph.yml
Labels: Type: Bug

#1714 [SUBGRAPH-OPS] Update deploy.sh
  packages/subgraph/tasks/deploy.sh
Labels: Project: SUBGRAPH, Team: Protocol

#1707 [ETHEREUM-CONTRACTS] BatchLiquidator: don't revert for non-transferrable SuperTokens
  packages/ethereum-contracts/contracts/utils/BatchLiquidator.sol
  packages/ethereum-contracts/test/foundry/utils/BatchLiquidator.t.sol
Labels: Type: Bug, Severity: Medium, Team: Protocol

#1718 [SDK-CORE] patch getUnderlyingToken
  packages/sdk-core/CHANGELOG.md
  packages/sdk-core/contracts/NoGetUnderlyingToken.sol
  packages/sdk-core/package.json
  packages/sdk-core/src/SuperToken.ts
  packages/sdk-core/src/utils.ts
  packages/sdk-core/test/1.0_supertoken.test.ts
Labels: Type: Bug, Project: SDK-CORE

#1730 [ETHEREUM-CONTRACTS] make deploy script compatible with ethers v6
  packages/ethereum-contracts/CHANGELOG.md
  packages/ethereum-contracts/dev-scripts/deploy-contracts-and-token.js
  packages/ethereum-contracts/dev-scripts/deploy-test-framework.js
  packages/ethereum-contracts/dev-scripts/index.js
  packages/ethereum-contracts/package.json
Labels: Type: Bug, Tag: TechDebt, Project: PROTOCOL-EVMv1, Team: Protocol

#1738 [WORKFLOWS] update deploy.sh
  packages/subgraph/tasks/deploy.sh
Labels: Project: SUBGRAPH
